version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  # server:
  #   build:
  #     context: ./
  #     target: production-build-stage
  #     dockerfile: ./Dockerfile
  #   container_name: server
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: on-failure
  #   networks:
  #     - backend
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #     - redis
  #     - spreadsheet-api-service
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=P@55word12345
    - POSTGRES_USER=dev
    - POSTGRES_DB=dev
    networks:
      - backend
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
  spreadsheet-api-service:
    image: trsiddiqui1989/ej2-spreadsheet-web-services
    restart: always
    ports:
      - '8080:80'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  redis:
    driver: local
