import { config } from 'dotenv'
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` })

export const CREDENTIALS = process.env.CREDENTIALS === 'true'
export const {
  NODE_ENV,
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  TENANT_ID,
  CLIENT_ID,
  CLIENT_CREDENTIALS,
  DRIVE_ID,
  TEMP_QUICKBOOKS_CLIENT_ID,
  TEMP_QUICKBOOKS_CLIENT_SECRET,
  TEMP_QUICKBOOKS_APPLICATION_ID,
  QUICKBOOKS_CALLBACK_API,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  BUCKET_NAME,
} = process.env
