import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('entities', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable()
    table.string('name').notNullable()
    table.boolean('isPrimary').defaultTo(false).notNullable()
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('archivedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('archivedBy').notNullable()
    table.unique(['uuid'])
  })
  await knex.schema.createTable('labels', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable()
    table.string('label').notNullable()
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('archivedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('archivedBy').notNullable()
    table.unique(['uuid'])
  })
  await knex.schema.createTable('categories', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable()
    table.string('name').notNullable()
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('archivedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('archivedBy').notNullable()
    table.unique(['uuid'])
  })
  await knex.schema.createTable('files', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable().primary()
    table.text('name').notNullable()
    table.text('location').notNullable()
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('archivedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('archivedBy').notNullable()
    table.unique(['uuid'])
  })

  await knex.schema.createTable('supporting_packages', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable().primary()
    table.bigInteger('entityID').notNullable().references('id').inTable('public.entities')
    table.bigInteger('categoryID').notNullable().references('id').inTable('public.categories')
    table.string('title').nullable()
    table.string('number').nullable()
    table.boolean('isConfidential').defaultTo(false).notNullable()
    table.string('journalNumber').nullable()
    table.timestamp('date').notNullable()
    table.bigInteger('approverID').notNullable().references('id').inTable('public.users')
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.unique(['uuid'])
  })

  await knex.schema.createTable('supporting_packages_communications', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigIncrements('uuid').notNullable().primary()
    table.bigInteger('supportingPackageID').notNullable().references('id').inTable('public.supporting_packages')
    table.string('cellLink')
    table.text('text').notNullable()
    table.string('attachmentLink')
    table.integer('order')
    table.boolean('isChangeRequest').defaultTo(false)
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('archivedAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('archivedBy').notNullable()
    table.unique(['uuid'])
  })

  await knex.schema.createTable('communications_users', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigInteger('communicationID').notNullable().references('id').inTable('public.supporting_packages_communications')
    table.bigInteger('userID').notNullable().references('id').inTable('public.files')
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('deleteAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('deletedBy').notNullable()
  })

  await knex.schema.createTable('supporting_packages_participants', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigInteger('supportingPackageID').notNullable().references('id').inTable('public.supporting_packages')
    table.bigInteger('userID').notNullable().references('id').inTable('public.files')
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('deleteAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('deletedBy').notNullable()
  })
  await knex.schema.createTable('supporting_packages_attachments', (table) => {
    table.bigIncrements('id').notNullable().primary()
    table.bigInteger('supportingPackageID').notNullable().references('id').inTable('public.supporting_packages')
    table.bigInteger('fileID').notNullable().references('id').inTable('public.users')
    table.boolean('isMaster').defaultTo(false).notNullable()
    table.timestamp('createdAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.timestamp('deleteAt').notNullable().defaultTo(knex.fn.now())
    table.string('createdBy').notNullable()
    table.string('updatedBy').notNullable()
    table.string('deletedBy').notNullable()
  })

}


export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable('entities')
  await knex.schema.dropTable('labels')
  await knex.schema.dropTable('categories')
  await knex.schema.dropTable('files')
  await knex.schema.dropTable('supporting_packages')
  await knex.schema.dropTable('supporting_packages_participants')
  await knex.schema.dropTable('supporting_packages_attachments')
  await knex.schema.dropTable('communications_users')
  await knex.schema.dropTable('supporting_packages_communications')
}

